# Generated by Django 3.2.9 on 2022-01-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='game_type',
        ),
    ]
